import { Injectable } from '@nestjs/common'
import { PrismaService } from '../prisma.service.js'

interface ChatMessage {
  role: 'user' | 'assistant'
  content: string
}

export interface DianaAction {
  type: 'create_project' | 'create_document' | 'none'
  payload?: Record<string, string>
}

export interface DianaResult {
  response: string
  action: DianaAction
}

@Injectable()
export class DianaService {
  constructor(private prisma: PrismaService) {}

  /**
   * Detect intent and return response + optional action
   */
  generateResult(userMessage: string, history: ChatMessage[] = []): DianaResult {
    const msg = userMessage.toLowerCase().trim()
    const prevUserMessages = history.filter((m) => m.role === 'user').map((m) => m.content)
    const isReturningUser = prevUserMessages.length > 1

    const hasDiscussedProject = history.some(
      (m) => m.content.toLowerCase().includes('project') || m.content.toLowerCase().includes('build')
    )

    // --- Create project intent ---
    const createProjectIntent =
      (msg.includes('create') || msg.includes('new') || msg.includes('start') || msg.includes('make')) &&
      msg.includes('project')

    if (createProjectIntent) {
      // Extract project name from message
      const nameMatch = userMessage.match(/(?:called|named|for|about)\s+["']?([^"'\n,]+)["']?/i)
      const projectName = nameMatch ? nameMatch[1].trim() : 'New Project'

      return {
        response: `I've created a project called **"${projectName}"** for you.\n\nHere's how I'd structure it:\n\n1. **Define the goal** — What does success look like?\n2. **Identify the first milestone** — What's the first thing that proves the idea works?\n3. **List the blockers** — What could prevent progress?\n\nYour project is saved and ready. What should we tackle first?`,
        action: { type: 'create_project', payload: { name: projectName, description: userMessage } },
      }
    }

    // --- Create document intent ---
    const createDocumentIntent =
      (msg.includes('create') || msg.includes('write') || msg.includes('draft') || msg.includes('generate') || msg.includes('make')) &&
      (msg.includes('document') || msg.includes('doc') || msg.includes('spec') || msg.includes('plan') || msg.includes('notes'))

    if (createDocumentIntent) {
      const titleMatch = userMessage.match(/(?:called|named|for|about|titled)\s+["']?([^"'\n,]+)["']?/i)
      const docTitle = titleMatch ? titleMatch[1].trim() : 'New Document'

      const content = `# ${docTitle}\n\n*Generated by Diana on ${new Date().toLocaleDateString()}*\n\n## Overview\n\nThis document was created from your conversation with Diana.\n\n## Purpose\n\n${userMessage}\n\n## Next Steps\n\n- [ ] Review and refine this document\n- [ ] Share with your team\n- [ ] Set a review date\n`

      return {
        response: `I've created a document called **"${docTitle}"** and saved it to your workspace.\n\nYou can find it in your documents list. Would you like me to add specific sections or expand any part of it?`,
        action: { type: 'create_document', payload: { title: docTitle, content } },
      }
    }

    // --- All other intents (pure conversation) ---
    return {
      response: this.generateResponse(userMessage, history),
      action: { type: 'none' },
    }
  }

  /**
   * Generate a context-aware conversational response
   */
  generateResponse(userMessage: string, history: ChatMessage[] = []): string {
    const msg = userMessage.toLowerCase().trim()
    const prevUserMessages = history.filter((m) => m.role === 'user').map((m) => m.content)
    const isReturningUser = prevUserMessages.length > 1

    const hasDiscussedProject = history.some(
      (m) => m.content.toLowerCase().includes('project') || m.content.toLowerCase().includes('build')
    )

    if (msg.includes('project') || msg.includes('build')) {
      if (hasDiscussedProject && isReturningUser) {
        return `We were talking about your project — let me continue from there.\n\nTo make this concrete, I suggest we define three things:\n\n1. **What problem does it solve?**\n2. **Who is the first user?**\n3. **What does success look like in 30 days?**\n\nAnswer whichever feels most important right now.`
      }
      return `Let's build this together.\n\nA strong project starts with three questions:\n\n1. **What problem are you solving?**\n2. **Who is the first person this helps?**\n3. **What would a working version look like in 2 weeks?**\n\nTell me about the problem first — everything else follows from that.`
    }

    if (msg.includes('document') || msg.includes('write') || msg.includes('draft')) {
      return `I can help you create that.\n\nTell me:\n- **What's the document for?** (specification, plan, notes, proposal)\n- **Who will read it?**\n- **What's the core message?**\n\nI'll draft it and save it to your workspace.`
    }

    if (msg.includes('help') || msg.includes('what can you do') || msg.includes('who are you')) {
      return `I'm Diana — your AI companion inside AIGINVEST.\n\nHere's what I can do right now:\n\n- **Create projects** — say "create a project called X"\n- **Generate documents** — say "write a plan for X"\n- **Think through ideas** — I ask the right questions\n- **Remember context** — I keep track of what we've discussed\n\nWhat would you like to work on?`
    }

    if (msg.includes('remember') || msg.includes('last time') || msg.includes('before') || msg.includes('earlier')) {
      if (prevUserMessages.length > 0) {
        const lastTopic = prevUserMessages[prevUserMessages.length - 2] || prevUserMessages[0]
        return `Yes — earlier you mentioned: *"${lastTopic.slice(0, 80)}${lastTopic.length > 80 ? '...' : ''}"*\n\nShall we continue from there, or is there something new you'd like to explore?`
      }
      return `This is the beginning of our conversation, so I'm starting fresh. But from this point forward, I'll remember everything you tell me in this session.\n\nWhat's on your mind?`
    }

    if (msg.includes('task') || msg.includes('todo') || msg.includes('organize')) {
      return `Organizing work well makes everything easier.\n\nLet's create a task list. Tell me:\n- **What's the goal?**\n- **What are the three most important things to accomplish?**\n\nI'll help you prioritize and sequence them.`
    }

    if (msg.includes('learn') || msg.includes('explain') || msg.includes('how') || msg.includes('what is')) {
      return `Good question. Let me break this down clearly.\n\nTo give you a useful answer, could you tell me a bit more about your background with this topic? That way I can pitch the explanation at exactly the right level.`
    }

    if (msg.includes('thank') || msg.includes('great') || msg.includes('perfect') || msg.includes('good')) {
      return `Happy to help. That's what I'm here for.\n\nWhat's the next thing you'd like to tackle?`
    }

    if (isReturningUser && hasDiscussedProject) {
      return `Building on what we've discussed — here's how I'd think about this: start with the smallest version that proves the idea works. What's blocking you right now?`
    }

    return `That's a good direction to explore.\n\nLet me ask you one clarifying question: what would a successful outcome look like for you here?\n\nOnce I understand what "done" means, I can give you much more specific help.`
  }

  /**
   * Get full conversation history from DB for context
   */
  async getConversationContext(conversationId: string): Promise<ChatMessage[]> {
    const messages = await this.prisma.message.findMany({
      where: { conversationId, deletedAt: null },
      orderBy: { createdAt: 'asc' },
      take: 20,
    })
    return messages.map((m) => ({ role: m.role as 'user' | 'assistant', content: m.content }))
  }

  /**
   * Main entry: generate Diana's response with full context
   */
  async respond(conversationId: string, userMessage: string): Promise<DianaResult> {
    const history = await this.getConversationContext(conversationId)
    return this.generateResult(userMessage, history)
  }
}
