#!/bin/bash
# Cron Job Setup Script
# Configures automated backups on a Linux/Unix server

set -e

BACKUP_SCRIPT="/opt/aig-platform/scripts/backup-database.sh"
BACKUP_DIR="/backups/postgresql"
BACKUP_USER="backup"
CRON_FILE="/etc/cron.d/aig-platform-backup"

echo "============================================================"
echo "Setting up Automated Database Backups"
echo "============================================================"

# Verify backup script exists
if [ ! -f "$BACKUP_SCRIPT" ]; then
  echo "❌ ERROR: Backup script not found: $BACKUP_SCRIPT"
  exit 1
fi

# Create backup directory
echo "Creating backup directory: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
chmod 700 "$BACKUP_DIR"

# Create backup user if needed
if ! id "$BACKUP_USER" &>/dev/null; then
  echo "Creating backup user: $BACKUP_USER"
  useradd -m -s /bin/bash "$BACKUP_USER" || true
fi

# Set permissions
chown "$BACKUP_USER:$BACKUP_USER" "$BACKUP_DIR"

# Make scripts executable
chmod +x /opt/aig-platform/scripts/*.sh

# Create cron job configuration
echo "Setting up cron jobs..."

# Backup configurations:
# - Hourly: 0 */1 * * * (top of every hour)
# - Daily: 0 2 * * * (2 AM every day)  
# - Weekly: 0 3 * * 0 (3 AM Sunday)

cat > "$CRON_FILE" << 'EOF'
# AIGINVEST Automated Backup Jobs
# DO NOT EDIT THIS FILE DIRECTLY - Use setup script

# Daily backup at 2 AM UTC
# 0 2 * * * backup /opt/aig-platform/scripts/backup-database.sh >> /var/log/aig-backup.log 2>&1

# Hourly backup (for high-frequency environments)
# 0 */1 * * * backup /opt/aig-platform/scripts/backup-database.sh >> /var/log/aig-backup.log 2>&1

# Weekly full backup with S3 upload at 3 AM Sunday
# 0 3 * * 0 backup /opt/aig-platform/scripts/backup-database.sh >> /var/log/aig-backup.log 2>&1

# Daily backup verification at 4 AM
# 0 4 * * * backup /opt/aig-platform/scripts/verify-backup.sh /backups/postgresql/$(date -d 'today' +\%Y\%m\%d)*.sql* >> /var/log/aig-backup-verify.log 2>&1

# Cleanup old backups (keep 30 days) - runs at 5 AM daily
# 0 5 * * * backup find /backups/postgresql -name "*.sql*" -mtime +30 -delete >> /var/log/aig-backup-cleanup.log 2>&1

# Environment variables for backup script
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
BACKUP_DIR=/backups/postgresql
DB_HOST=localhost
DB_PORT=5432
DB_NAME=aig_platform
DB_USER=aig_user
RETENTION_DAYS=30
S3_BUCKET=aig-platform-backups
S3_REGION=eu-central-1
BACKUP_COMPRESSION=gzip
EOF

echo "✓ Cron configuration file created: $CRON_FILE"

# Print cron job suggestions
echo ""
echo "============================================================"
echo "Recommended Cron Jobs (uncomment in $CRON_FILE)"
echo "============================================================"
echo ""
echo "Daily Backup (2 AM UTC):"
echo "  0 2 * * * backup /opt/aig-platform/scripts/backup-database.sh"
echo ""
echo "Hourly Backup (recommended for production):"
echo "  0 */1 * * * backup /opt/aig-platform/scripts/backup-database.sh"
echo ""
echo "Weekly Full Backup with S3 (3 AM Sunday):"
echo "  0 3 * * 0 backup /opt/aig-platform/scripts/backup-database.sh"
echo ""
echo "Daily Backup Verification (4 AM UTC):"
echo "  0 4 * * * backup find /backups/postgresql -name '*.sql*' -mtime -1 -exec /opt/aig-platform/scripts/verify-backup.sh {} \;"
echo ""
echo "============================================================"
echo "Setup Verification"
echo "============================================================"
echo ""

# Verify setup
echo "✓ Backup script: $([ -x $BACKUP_SCRIPT ] && echo 'Executable' || echo 'Not executable')"
echo "✓ Backup directory: $([ -d $BACKUP_DIR ] && echo 'Exists' || echo 'Missing')"
echo "✓ Backup user: $([ $(id -u $BACKUP_USER 2>/dev/null || echo -1) -ge 0 ] && echo 'Exists' || echo 'Missing')"
echo "✓ Cron file: $([ -f $CRON_FILE ] && echo 'Created' || echo 'Failed')"

echo ""
echo "============================================================"
echo "Next Steps"
echo "============================================================"
echo "1. Edit $CRON_FILE to uncomment desired backup schedules"
echo "2. Verify PostgreSQL credentials are set correctly"
echo "3. Configure AWS credentials for S3 uploads (if using)"
echo "4. Test backup manually: $BACKUP_SCRIPT"
echo "5. Monitor logs: tail -f /var/log/aig-backup*.log"
echo "============================================================"
